### ISSUE TITLE
No module named 'dynaconf'

### ISSUE THREAD

**Issue by medeirosjrm** [rochacbruno/python-week-2022#4]
Depois de clonar o repositório git, entrei no diretório /python-week-2022
Ao executar  python -m beerlog

recebi o erro 

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/python-week-2022/beerlog/__main__.py", line 1, in <module>
    from .cli import main
  File "/root/python-week-2022/beerlog/cli.py", line 1, in <module>
    from .config import settings
  File "/root/python-week-2022/beerlog/config.py", line 2, in <module>
    from dynaconf import Dynaconf

**ModuleNotFoundError: No module named 'dynaconf'**

########Solução###########
A solução foi apenas instalar o modulo dynaconf com o commando ,

pip install dynaconf

Installing collected packages: dynaconf
Successfully installed dynaconf-3.1.8

Ao executar novamente o comando  -->  python3 -m beerlog
Hello from beerlog

**Comment by rochacbruno** [comment]
Olá @medeirosjrm nós vamos usar o `poetry` para gerenciar as dependencias do projeto.

rodando `poetry install` ele já instala as libs que estão definidas em `pyproject.toml`

**Comment by rochacbruno** [comment]
https://github.com/rochacbruno/python-week-2022#requisitos

**Comment by medeirosjrm** [comment]
show!
